<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="1" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="22230" started-at="2016-08-25T16:59:02Z" finished-at="2016-08-25T16:59:25Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="22230" started-at="2016-08-25T16:59:02Z" finished-at="2016-08-25T16:59:25Z">
      <class name="testcases.VerifyLoginPageWithCaptureOnFailure">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testcases.VerifyLoginPageWithCaptureOnFailure@18be83e4]" name="setUp" is-config="true" duration-ms="14262" started-at="2016-08-25T22:29:02Z" finished-at="2016-08-25T22:29:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testHomePage()[pri:0, instance:testcases.VerifyLoginPageWithCaptureOnFailure@18be83e4]" name="testHomePage" duration-ms="7863" started-at="2016-08-25T22:29:17Z" finished-at="2016-08-25T22:29:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testHomePage -->
        <test-method status="FAIL" signature="tearDown(org.testng.ITestResult)[pri:0, instance:testcases.VerifyLoginPageWithCaptureOnFailure@18be83e4]" name="tearDown" is-config="true" duration-ms="0" started-at="2016-08-25T22:29:25Z" finished-at="2016-08-25T22:29:25Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[wrong number of arguments]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.afterRun(TestRunner.java:1021)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.VerifyLoginPageWithCaptureOnFailure -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
